




















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `mssql`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=192.168.2.251;Initial Catalog=THOA_Mall;User ID=sa;Password=taihao123Aa`
//     Schema:                 ``
//     Include Views:          `False`











































